from typing import Any
import numpy as np

class Quat:
    def __init__(self, scalar: float, vx: float, vy: float, vz: float) -> None: ...
    def __repr__(self) -> str: ...
    def __mul__(self, other: Quat) -> Quat: ...
    def rotate(self, vec: np.ndarray) -> np.ndarray: ...
    def normalize(self) -> Quat: ...
    def normalize_large(self) -> Quat: ...
    def normalized(self) -> Quat: ...
    def normalized_large(self) -> Quat: ...
    def conjugated(self) -> Quat: ...
    def copy(self) -> Quat: ...
    def tobytes(self) -> bytes: ...
    def lerp(self, other: Quat, t: float) -> Quat: ...
    def slerp(self, other: Quat, t: float) -> Quat: ...
    def dot(self, other: Quat) -> float: ...
    def to_vector(self) -> np.ndarray: ...

def big_omega(w: np.ndarray) -> np.ndarray: ...
def skew(w: np.ndarray) -> np.ndarray: ...
def valenti_q_mag(ary: np.ndarray) -> Quat: ...
def valenti_dq_mag(ary: np.ndarray) -> Quat: ...
def valenti_q_acc(ary: np.ndarray) -> Quat: ...
def valenti_dq_acc(ary: np.ndarray) -> Quat: ...